### ISSUE TITLE
Trabsformação com CSS puro e HTML sem uso de JavaScript

### ISSUE THREAD

**Issue by laisqueiroz** [laisqueiroz/ProjetoFinal_LMS#3]
A transformação pode ser 2D ou 3D.

Segue links de documentação da W3Schools.

Transformações 2D
https://www.w3schools.com/css/css3_2dtransforms.asp

Transformações 3D
https://www.w3schools.com/css/css3_3dtransforms.asp

**Comment by Juandbpimentel** [comment]
Eu implementei a transformação nos cards da minha tela, então vou fechar aqui o Isue
